background            #1D2021
foreground            #DDC7A1
cursor                #D4BE98
cursor_text_color     #1D2021
selection_background  #2E3B3B
selection_foreground  #DDC7A1

url_color              #7DAEA3

active_tab_background  #3C3836
active_tab_foreground  #DDC7A1
inactive_tab_background #1D2021
inactive_tab_foreground #928374

active_border_color    #7DAEA3
inactive_border_color  #504945
bell_border_color      #D8A657

mark1_foreground #1D2021
mark1_background #D3869B

color0   #1D2021  
color1   #EA6962  
color2   #A9B665  
color3   #D8A657  
color4   #7DAEA3  
color5   #D3869B  
color6   #89B482  
color7   #D4BE98  

color8   #504945  
color9   #EA6962  
color10  #A9B665  
color11  #D8A657  
color12  #7DAEA3  
color13  #D3869B  
color14  #89B482  
color15  #DDC7A1  

notification_background #1D2021
notification_foreground #DDC7A1
notification_button_background #3C3836
notification_button_foreground #DDC7A1

scrollbar_background #1D2021
scrollbar_foreground #504945

