# Themes & Appearance
include gruvbox-material.conf
# include nordic.conf  # Uncomment for "nordic" theme

# Font Settings
font_family               JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0
adjust_line_height 110%
adjust_column_width 102%

# Window Settings
hide_window_decorations yes
tab_bar_edge top
tab_bar_style separator
tab_separator "|"
window_padding_width 25
background_opacity 0.90
background_blur 10

# Disable closing prompt
confirm_os_window_close 0
